### ISSUE TITLE
bug(commonmark) Toggle modes reorders markdown links

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#163]
**Describe the bug**
Commonmark toggle reorders markdown links to be in alphabetical instead of natural order

**To Reproduce**
Enter text in markdown:
```
Here is [a link][180]. And a [second link][1]. And [a third][21] 

[180]: https://stackoverflow.com
[1]: https://stackexchange.com
[21]: https://google.com
```

Switch to rich text and back to markdown.

**Expected behavior**
Expect it to be in identical order when switched back. Instead is now like this:

```
Here is [a link][180]. And a [second link][1]. And [a third][21]

[1]: https://stackexchange.com
[180]: https://stackoverflow.com
[21]: https://google.com
```

**Screenshots**
![image](https://i.stack.imgur.com/Zi7Wa.gif)

**Additional context**
- [MSE Link](https://meta.stackexchange.com/a/380305/51)
- user identified [this line](https://github.com/StackExchange/Stacks-Editor/blob/d6de2d4bfca63a6a7b9c729c2747833bf91aa777/src/shared/markdown-serializer.ts#L70) as the culprit

**Comment by double-beep** [comment]
@b-kelly the issue asked that the original order shouldn't change after switching back to markdown mode. Note that ["Toggling between Markdown and rich text to preview the result without editing anything should not be a destructive action"](https://meta.stackexchange.com/a/360159).

**Comment by b-kelly** [comment]
@double-beep 100% agreed that the document should very largely go back to what it was on serialization, but unfortunately the parser doesn't give me nearly enough info about biblio links to make this a reality. The current implementation places all biblio links at the bottom, regardless of original placement. This is a compromise since our two options are "no support" and "partial support". This PR further augments that compromise to make it slightly more bearable.

I've been doing some research on markdown parsers that produce a Concrete Syntax Tree (vs an Abstract Syntax Tree) and it would seem that there currently aren't any. We don't currently have the resources to produce or maintain such a library, so "perfect/lossless" support for a lot of different syntax will have to remain at 75-95% correctness until that point. Typically, the shortcomings tend to fall under edge cases, so it has been a rather reasonable decision so far.
