### ISSUE TITLE
bug(commonmark) markdown to rich text toggle combines adjacent indented code blocks

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#168]
**Describe the bug**
Code blocks created in rich text mode are translated into indented code blocks in markdown mode.

Adjacent indented code blocks in markdown mode are translated into one code block in rich text (when separated by a new line), which is per-spec.

Solution may be that when translating a code block from rich text to markdown, it should be as a fenced code block and not as an indented code block.

**To Reproduce**
1. In RT mode, add two lines of text
2. Highlight the first, and ctrl-m to make into a code-block. Repeat for the second line
3. Toggle to MD
4. Toggle back to RT
5. They are now one code block

**Expected behavior**
Individual adjacent code blocks should remain distinct when round-tripping

**Screenshots**
![screenshot](https://i.stack.imgur.com/9k0Jn.gif)

**Desktop (please complete the following information):**
 - Windows Chrome 103

**Additional context**
[MSE post](https://meta.stackexchange.com/a/380302/51)

**Comment by yellis** [comment]
@b-kelly to look into commonmark spec to verify how this works per spec

**Comment by b-kelly** [comment]
Indented code blocks merging on deserialization is [by design](https://spec.commonmark.org/0.30/#example-111), however, I would agree that the serialization step is not producing the user anticipated markdown. I'd like to encourage use of code fences anyways, so I think making the fences the default serialization version would be the correct solution here.
