### ISSUE TITLE
Css isolation help angular

### ISSUE THREAD

**Issue by thiagocleite** [StackExchange/Stacks-Editor#239]
I'd like to use StacksEditor in my project angular . However i have some problem with css isolation, because css used in StackEdit start to get html structure root as result of this my website was broken. There is a css file in repo to handle it? Or some sugestions? I tried to use ShadowRoot but no success.

**Comment by giamir** [comment]
As of today, Stacks Editor expects stacks.css and stacks.js to be included in the page where it is rendered. 
See [this part](https://github.com/StackExchange/Stacks-Editor#import-via-modules-or-commonjs) of the readme for more details. I am closing this issue for now since I don't think there is much we can do from our end.
