### ISSUE TITLE
Urls cause tables to misalign

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#37]
Reported on [Meta.SE](https://meta.stackexchange.com/a/361096/395497)

**Describe the bug**

> I attempted to create this table with URLs in the first column:
> [![enter image description here][1]][1]
> 
> Adding the URLs to the text causes the table formatting to break. Cells become misaligned. This happens when you are creating/editing the table via rich text and when you are using markdown.
> [![enter image description here][2]][2]
> 
> Steps to repro:
> Create table, add URL to text either via markdown or using the "insert link" icon
> 
> | Column A | Column B |
> | -------- | -------- |
> | [Cell 1](https://meta.stackexchange.com/questions/360033/opt-in-alpha-test-for-a-new-stacks-editor/361096#361096) | Cell 2   |
> | Cell 3   | Cell 4   |
> 
> **Was able to do this successfully in MSE editor, had misalignment issue in Teams editor**
> 
>   [1]: https://i.stack.imgur.com/nhda4.png
>   [2]: https://i.stack.imgur.com/lr5LB.png

**To Reproduce**

Use the following markdown:

```markdown
| Column A | Column B |
| -------- | -------- |
| [Cell 1](https://meta.stackexchange.com/questions/360033/opt-in-alpha-test-for-a-new-stacks-editor/361096#361096) | Cell 2   |
| Cell 3   | Cell 4   |
```

**Comment by hamvocke** [comment]
I was able to reproduce this issue on Teams, but not on the Stacks-Editor tables playground.

The culprit seems to be a dangling `div.js-placeholder` element that gets inserted before the two table cells in the affected row:

![Screenshot 2022-04-29 at 16 04 34](https://user-images.githubusercontent.com/491469/165960844-a1702321-53e2-4571-81e2-80e3ef38c2e0.png)

![Screenshot 2022-04-29 at 16 04 40](https://user-images.githubusercontent.com/491469/165960865-1b93fcaa-905b-4a9e-8759-003c34d27732.png)

Here's the full markup I got for the faulty table:

```html
<table class="s-table">
  <thead>
    <tr>
      <th markup="">Column A</th>
      <th markup="">Column B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <div class="js-placeholder ProseMirror-widget" contenteditable="false"></div> <!-- this is the one causing trouble -->
      <td markup="">
        <a href="https://meta.stackexchange.com/questions/360033/opt-in-alpha-test-for-a-new-stacks-editor/361096#361096">Cell 1</a>
      </td>
      <td markup="">Cell 2</td>
    </tr>
    <tr>
      <td markup="">Cell 3</td>
      <td markup="">Cell 4</td>
    </tr>
  </tbody>
</table>
```

That `.js-placeholder` element doesn't seem to be there in our tables playground but only appears on Stack Overflow.

Searching through the Stacks-Editor codebase for `js-placeholder` doesn't yield any results which makes me think it's not generated by Stacks-Editor. On the other hand, it gets a `ProseMirror-widget` class which makes me think it must be coming from the editor itself.

Does this ring any bell? Could this be some other part of Stacks (or Stack Overflow's global JS) clashing with Stacks-Editor? Oneboxes maybe?

**Comment by b-kelly** [comment]
I can repro in the reference editor with the following markdown:

```markdown
| Column A | Column B |
| --- | --- |
| [Cell 1](https://example.com/foo/bar) | Cell 2 |
| Cell 3 | Cell 4 |
```

![image](https://user-images.githubusercontent.com/14169651/168147722-0dd87c87-d7cc-4a6a-a537-3996c44644e3.png)
