### ISSUE TITLE
Editor menu bar looks and is not working?

### ISSUE THREAD

**Issue by iwasherefirst2** [StackExchange/Stacks-Editor#80]
**Describe the bug**
I don't think that this is a bug, I suspect that I have done something wrong, but I am not sure what. When I follow the setup instructions, the editor looks like this:
![image](https://user-images.githubusercontent.com/1765602/132096802-831d2469-01a3-40be-a03f-68710168ad5f.png)

When I click on the markdown checkbox, then I just get this:
![image](https://user-images.githubusercontent.com/1765602/132096821-9faa6ab6-00c3-4891-b857-707c3c792355.png)

and the rest of the editor is gone

**To Reproduce**

   1. npm install @stackoverflow/stacks-editor
    2. copied node_modules/@stackoverflow/dist/styles.css into /css/stack.editor.css.
    3. copied node_modules/@stackoverflow/dist/app.bundle.js into /js/app.bundle.js
Step 4 Use this HTML:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/stack-editor.css" rel="stylesheet">
    <script src="/js/app.bundle.js"></script>
    <title>Stack Editor</title>
</head>
<body>
<div id="editor-container"></div>
<script>
    new window.stacksEditor.StacksEditor(
        document.querySelector("#editor-container"),
        "*Your* **markdown** here",
        {}
    );
</script>
</body>
</html>
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/1765602/132096949-b2644626-3c64-4722-a913-c88d4adcc270.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox 91.0.2 (64-bit) and  Chrome Version 91.0.4472.114 (Official Build) (64-bit)

**Additional context**
The css and js are actually loaded. If I remove one of them, nothing works. I also checked in network tab that both are loaded. There are no warnings on the console.

I also tried to import via Modules but then it would crash on compiling: Module not found: Error: Can't resolve '@stackoverflow/stacks-editor/styles.css'

**Comment by b-kelly** [comment]
It looks like you're missing the core [Stacks](https://github.com/StackExchange/Stacks) library. This isn't included in the project dependencies because... reasons. We include this in the [demo site page](https://github.com/StackExchange/Stacks-Editor/blob/main/site/index.html#L10-L11) from a CDN, but it looks like I forgot to list it the README.

Thanks for the heads up! I'll file an issue here to either A) make changes to the README to make this obvious or B) include @stackoverflow/stacks as a peer dependency and update the docs/package to reflect that.

As a general heads up, we don't use this npm package much outside of our internal build process, so it is a bit untested. If there's anything else "odd" about it that keeps you from using it efficiently, please let us know!

**Comment by b-kelly** [comment]
Closing in favor of #81. Please do not hesitate to reopen if the suggested fix does not work for you.

**Comment by iwasherefirst2** [comment]
@b-kelly  thank you so much! I will try it out.

**Comment by iwasherefirst2** [comment]
@b-kelly one more thing, I realized why import via Modules would crash on compiling with: `Module not found: Error: Can't resolve '@stackoverflow/stacks-editor/styles.css'`.

It think because the line should be 

```
import "@stackoverflow/stacks-editor/dist/styles.css";
```

You want me to create a MR for this?

**Comment by b-kelly** [comment]
@iwasherefirst2 Nice catch! No need for a PR, I went ahead and fixed it up. For such a small change, it would take me longer to review and merge the PR than it would be for me to just commit the fix 😉
