### ISSUE TITLE
Improve docs/readme for inclusion of core Stacks library

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#81]
**Is your feature request related to a problem? Please describe.**

The core Stacks library is required for this package. It provides critical styles and JS functionality (popovers, mostly). However, the README does not reflect this and the `@stackoverflow/stacks` package is not included in package.json as a production or peer dependency.

**Describe the solution you'd like**

Either update the docs/readme to reflect needing to pull in Stacks _or_ add the package as a dependency of some sort so it gets bundled.

**Comment by bharney0** [comment]
@b-kelly on of the issues I faced when trying to include the @stackoverflow/stacks package with the editor, was that in our project we are incapsulating all of the editor logic into a web-component. But when I tried to import stacks into a `.ts` file, its not compatible with imports because it is a UMD module. And this requires us to add an additional script tag for stacks. Instead of just importing one bundle containing stacks-editor web-component.

**Comment by b-kelly** [comment]
@bharney0 Agreed, we have that problem internally as well. I've taken a stab at fixing this in the past in StackExchange/Stacks#707, but never buckled down to finish the final 20% of the work. We'll be needing this fixed internally soon as well, so expect some movement on that front relatively soon.

**Comment by b-kelly** [comment]
@bharney0 Heads up - Stacks is now a properly bundled module, so es6 imports and TS types finally work!
